# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  semversion: '0.5'

stages:
- stage: Build
  displayName: Build Helmspace image
  jobs:  
  - job: Build
    displayName: Build Helmspace Image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build Helmspace image
      inputs:
        containerRegistry: 'Docker_Hub_bhsonu'
        repository: 'bhsonu/helmspace'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(semversion).$(tag)
    - task: Docker@2
      displayName: Push helmspace image to DockerHub
      inputs:
        containerRegistry: 'Docker_Hub_bhsonu'
        repository: 'bhsonu/helmspace'
        command: 'push'
        tags: '$(semversion).$(tag)'

- stage: deploy
  displayName: Deploy application
  jobs:
    - deployment: deployment1dev
      environment: 
        name: 'dev'
      strategy:
        runOnce:
          deploy:
            steps:
            - task: Bash@3
              displayName: 'Create deployment'
              inputs:
                targetType: 'inline'
                script: |
                  #!/bin/bash
                  echo "Deploying dev"

- stage: intgeration
  displayName: Integrationstage
  dependsOn: [Build] 
  jobs:
    - job: integrations
      steps:
      - task: Bash@3
        displayName: 'Create Integration'
        inputs:
          targetType: 'inline'
          script: |
            #!/bin/bash
            echo "Deploying dev"

- stage: Production
  displayName: Production stage
  dependsOn: [intgeration, deploy]
  jobs:
    - job: production
      steps:
      - task: Bash@3
        displayName: 'Create Integration'
        inputs:
          targetType: 'inline'
          script: |
            #!/bin/bash
            echo "Deploying dev"