# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  semversion: '0.5'

stages:
- stage: Build
  displayName: Build Helmspace image
  jobs:  
  - job: Build
    displayName: Build Helmspace Image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build Helmspace image
      inputs:
        containerRegistry: 'Docker_Hub_bhsonu'
        repository: 'bhsonu/helmspace'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(semversion).$(tag)
    - task: Docker@2
      displayName: Push helmspace image to DockerHub
      inputs:
        containerRegistry: 'Docker_Hub_bhsonu'
        repository: 'bhsonu/helmspace'
        command: 'push'
        tags: '$(semversion).$(tag)'