version: "3"

services:
  
  helmspace-app:
    build: 
      dockerfile: Dockerfile
      context: .

    environment:
      - CHART_MUSEUM_URL=http://localhost:9000
      - CHART_MUSEUM_API=/api/charts
    
      ports:
      - "5000:5000"